### PR TITLE
Fix author

### PR DESCRIPTION
**Pull request by LOCKEDFILE**
i written worng email.

### CODE REVIEW

**Comment by rodrigobastosv** [comment]
I'm a bit confused with this. This was already merged. Could you clarify what's this?

**Comment by LOCKEDFILE** [comment]
i want to chang author of commit. is it possible?

**Comment by rodrigobastosv** [comment]
I'm not sure if creating another PR is the best option here. It's strange that github is finding differences between the code and the master branch, but your code is already merged there. I think i will close this for now.

I think i added you as contributor right @LOCKEDFILE ?

**Comment by LOCKEDFILE** [comment]
oh im sorry. i  check now.

**Pull request closed without merging**
